In [2]:
import pandas as pd
import numpy as np

# Create a function named get_db_url.

#It should accept a username, hostname, password, and database name and return a url connection string formatted like in the example at the start of this lesson.

import env

In [5]:

    
url = env.get_db_url('employees')

In [6]:
#Use your function to obtain a connection to the employees database.

pd.read_sql('select * from employees', url)

        emp_no  birth_date first_name last_name gender   hire_date
0        10001  1953-09-02     Georgi   Facello      M  1986-06-26
1        10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2        10003  1959-12-03      Parto   Bamford      M  1986-08-28
3        10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4        10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12
...        ...         ...        ...       ...    ...         ...
300019  499995  1958-09-24     Dekang  Lichtner      F  1993-01-12
300020  499996  1953-03-07       Zito      Baaz      M  1990-09-27
300021  499997  1961-08-03    Berhard    Lenart      M  1986-04-21
300022  499998  1956-09-05   Patricia   Breugel      M  1993-10-13
300023  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30

[300024 rows x 6 columns]

In [ ]:
#Read the employees and titles tables into two separate DataFrames.

In [8]:
#Employees

employees_df = pd.read_sql('select * from employees', url)
employees_df

        emp_no  birth_date first_name last_name gender   hire_date
0        10001  1953-09-02     Georgi   Facello      M  1986-06-26
1        10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2        10003  1959-12-03      Parto   Bamford      M  1986-08-28
3        10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4        10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12
...        ...         ...        ...       ...    ...         ...
300019  499995  1958-09-24     Dekang  Lichtner      F  1993-01-12
300020  499996  1953-03-07       Zito      Baaz      M  1990-09-27
300021  499997  1961-08-03    Berhard    Lenart      M  1986-04-21
300022  499998  1956-09-05   Patricia   Breugel      M  1993-10-13
300023  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30

[300024 rows x 6 columns]

In [8]:
#Titles

url = env.get_db_url('employees.titles')

pd.read_sql('select * from titles', url)
#titles_df = pd.read_sql('select * from titles', url)
#titles_df

OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'tobias_2306'@'%%' to database 'employees.titles'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [ ]:
#How many rows and columns do you have in each DataFrame? Is that what you expected?

In [ ]:
#Display the summary statistics for each DataFrame.

In [ ]:
#How many unique titles are in the titles DataFrame?

In [ ]:
#What is the oldest date in the to_date column?

In [ ]:
#What is the most recent date in the to_date column?

In [ ]:
#

In [ ]:
#